FROM ubuntu:20.04
RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        curl \
        ca-certificates && \
# Install a recent version of Node.js.
# See https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
    cd /tmp && \
    curl -sLO https://deb.nodesource.com/setup_14.x && \
    bash setup_14.x && \
    rm setup_14.x && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        nodejs \
        build-essential && \
    rm -rf /var/lib/apt/lists/* && \
# Update npm.
    npm install -g npm
WORKDIR /app/
